# Generated by Django 4.2 on 2025-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='note',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='object_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='model',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('communicated', 'Communicated')], max_length=20),
        ),
    ]
