name: Django CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy project files to server
      run: |
        rsync -avz \
          --rsync-path="mkdir -p /root/Networking/dev/crm && rsync" \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./dev/crm/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/root/Networking/dev/crm/

    - name: Run remote deploy commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /root/Networking
          source venv/bin/activate
          pip install -r dev/crm/requirements.txt
          python dev/crm/manage.py migrate
          python dev/crm/manage.py collectstatic --noinput
          sudo systemctl restart django_crm
          sudo systemctl restart nginx
        EOF
